### ISSUE TITLE
能不能把你的插件打包发一下？

### ISSUE THREAD

**Issue by eicky** [mabeijianxi/android-automation#1]
由于这个插件很多都失败，所以请求把插件的目录发一下

**Comment by mabeijianxi** [comment]
http://updates.jenkins-ci.org/download/plugins,这里面可以手动下载所需要的，我也压缩了一份在本工程目录下面，手动安装比较麻烦，因为涉及到一些依赖，所以得有安装顺序。建议在页面上点击安装。
